import type { Species, Attribute, Role, Path, Skill, Weapon, Armor, Shield, EquipmentPack } from '../types/discordia';

export const SPECIES: Species[] = [
  {
    id: 'human',
    name: 'Umano',
    maxAge: 100,
    height: { female: '1.65m', male: '1.75m' },
    weight: { female: '65kg', male: '75kg' },
    attributeAdjustments: {},
    freeAttributeBonus: 1,
    skillBonuses: [],
    freeSkillBonuses: 2, // +2 to one, +1 to another
    speed: 5,
    essenceChoices: [['light', 'shadow']],
    essenceAlternative: '+1 Difesa',
    healthBonus: 1,
    languages: ['Kagari (lingua comune)', 'Una lingua a scelta'],
    specialTraits: [
      { name: 'Versatile', description: '+2 punti abilita aggiuntivi per livello' },
      { name: 'Apprendimento Rapido', description: 'Competenza extra ad ogni livello pari' },
    ],
  },
  {
    id: 'dwarf',
    name: 'Nano',
    maxAge: 500,
    height: { female: '1.25m', male: '1.35m' },
    weight: { female: '105kg', male: '135kg' },
    attributeAdjustments: { VIT: 1, STR: 1, AGI: -1, MIN: -1 },
    skillBonuses: [
      { skillId: 'enduring', bonus: 2 },
      { skillId: 'engineering', bonus: 1 },
    ],
    speed: 4,
    essenceChoices: [['earth'], ['fire']],
    essenceAlternative: '+1 punto abilita',
    healthBonus: 0,
    languages: ['Nanico', 'Kagari (lingua comune)'],
    specialTraits: [
      { name: 'Scurovisione', description: 'Vede perfettamente nel buio totale' },
      { name: 'Fermezza', description: 'Vantaggio sui check per evitare spinta/trazione/prone' },
      { name: 'Armi Culturali', description: '+1 bonus combattimento con martelli o asce' },
    ],
    curse: 'Legato al focolare del clan. Lasciarlo per >1 settimana causa debolezza; >1 mese e permanente.',
  },
  {
    id: 'elf',
    name: 'Elfo',
    maxAge: 1000,
    height: { female: '1.45m', male: '1.55m' },
    weight: { female: '36kg', male: '48kg' },
    attributeAdjustments: { FIN: 1, AGI: 1, MIN: 1, VIT: -2, STR: -1 },
    skillBonuses: [
      { skillId: 'charming', bonus: 2 },
      { skillId: 'focusing', bonus: 1 },
    ],
    speed: 5,
    essenceChoices: [['nature'], ['dream']],
    essenceAlternative: '+1 bonus combattimento',
    healthBonus: 0,
    languages: ['Elfico', 'Kagari (lingua comune)'],
    specialTraits: [
      { name: 'Sonno Elfico', description: 'Solo 4 ore di riposo necessarie' },
      { name: 'Mente Elfica', description: 'Vantaggio sui check contro controllo mentale' },
      { name: 'Armi Culturali', description: '+1 bonus combattimento con spade o archi' },
    ],
    curse: 'Tassi di natalita drasticamente ridotti.',
  },
  {
    id: 'kagari',
    name: 'Kagari',
    maxAge: 70,
    height: { female: '1.65m', male: '1.55m' },
    weight: { female: '55kg', male: '50kg' },
    attributeAdjustments: { SEN: 1, PRE: 1, STR: -1, VIT: -1 },
    skillBonuses: [
      { skillId: 'running', bonus: 2 },
      { skillId: 'sneaking', bonus: 1 },
    ],
    speed: 5,
    essenceChoices: [['water'], ['air']],
    essenceAlternative: '+1 Velocita',
    healthBonus: 0,
    languages: ['Kagari (lingua comune)'],
    specialTraits: [
      { name: 'Fuggitivo', description: 'Vantaggio sui check contro effetti che limitano il movimento' },
      { name: 'Inventivo', description: '+1 bonus combattimento con armi leggere e improvvisate' },
      { name: 'Cantastorie', description: 'Una volta al giorno, ispira una creatura: 1 livello di vantaggio su un check di abilita' },
    ],
    curse: 'Non puo restare nello stesso luogo >1 settimana. Perde 1 VIT/giorno dopo.',
  },
];

export const ATTRIBUTES: Attribute[] = [
  { id: 'STR', name: 'Forza', description: 'Potenza fisica, danno con alcune armi' },
  { id: 'FIN', name: 'Destrezza', description: 'Motricita fine, coordinazione, mira, combattimento a distanza' },
  { id: 'AGI', name: 'Agilita', description: 'Velocita, controllo del corpo, difesa, alcune armi' },
  { id: 'VIT', name: 'Vitalita', description: 'Salute, resistenza, influenza i PV' },
  { id: 'SEN', name: 'Sensi', description: 'Capacita percettive' },
  { id: 'PRE', name: 'Presenza', description: 'Carisma, influenza sociale' },
  { id: 'MIN', name: 'Mente', description: 'Potere mentale, usato da alcuni incantatori' },
  { id: 'REA', name: 'Ragione', description: 'Logica, intelletto, personaggi eruditi' },
];

export const ROLES: Role[] = [
  { id: 'warrior', name: 'Guerriero', combatBonus: 3, defenseBonus: 1, competencyFormula: '5 + REA', startingEssences: 0, availablePaths: ['arms_master', 'archer', 'berserker'] },
  { id: 'spellweaver', name: 'Tessitore', combatBonus: 0, defenseBonus: 0, competencyFormula: '5 + REA', startingEssences: 5, availablePaths: ['arcanist', 'summoner'] },
  { id: 'mystic', name: 'Mistico', combatBonus: 1, defenseBonus: 1, competencyFormula: '5 + REA', startingEssences: 3, availablePaths: ['paladin', 'priest'] },
  { id: 'scout', name: 'Esploratore', combatBonus: 2, defenseBonus: 1, competencyFormula: '5 + REA', startingEssences: 0, availablePaths: ['beastmaster', 'ranger'] },
  { id: 'agent', name: 'Agente', combatBonus: 1, defenseBonus: 1, competencyFormula: '5 + REA', startingEssences: 0, availablePaths: ['sentinel'] },
  { id: 'rogue', name: 'Furfante', combatBonus: 1, defenseBonus: 1, competencyFormula: '7 + REA', startingEssences: 0, availablePaths: ['swashbuckler', 'thief'] },
];

export const PATHS: Path[] = [
  {
    id: 'arcanist', name: 'Arcanista', roleId: 'spellweaver',
    armorTraining: 'Nessuna armatura',
    weaponTraining: 'Armi leggere',
    bonusCompetencies: ['Magia'],
    equipmentPacks: ["Pacco dello Studioso", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 3, essencesPerLevel: 2,
    essenceOptions: ['fire', 'water', 'air', 'earth'],
    spells: ['Dardo di Fiamma (fuoco)', 'Dardo di Gelo (acqua)', 'Controlla Venti (aria)', 'Incenerire (fuoco)', 'Fulmine ad Arco (aria)', 'Condotto (acqua)', 'Armatura di Sabbia (terra)', 'Brace di Xyra (fuoco)', 'Guida Acqua (acqua)', 'Levitare (aria)'],
    levelProgression: [
      { level: 1, combatBonus: 0, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Scegli 3 incantesimi'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: ['Ricorrenza Arcana'], specialAbilityChoice: false },
      { level: 3, combatBonus: 0, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 4, combatBonus: 0, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: ['Azzardo Arcano'], specialAbilityChoice: false },
      { level: 5, combatBonus: 0, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
    ],
    specialAbilities: ['Incantesimi Extra', 'Reindirizzamento Incantesimo', 'Scudo Arcano', 'Accordo Elementale', 'Cambio Focus', 'Sintonia Elementale', 'Studioso di Magia'],
  },
  {
    id: 'archer', name: 'Arciere', roleId: 'warrior',
    armorTraining: 'Armatura media',
    weaponTraining: 'Armi medie, Armi a distanza pesanti',
    bonusCompetencies: ['Guerra'],
    equipmentPacks: ["Pacco del Soldato", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 5, essencesPerLevel: 1,
    essenceOptions: ['earth', 'nature', 'shadow'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Posizione Elevata'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Tiro in Mischia'], specialAbilityChoice: false },
      { level: 4, combatBonus: 0, defenseBonus: 0, attributeBonus: 1, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Tiro Letale'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Mira Magistrale', 'Balistica Esperta', 'Tiro Pesante', 'Tiro a Cavallo', 'Arma Favorita', 'Addestramento Carico', 'Copertura Tattica', 'Tiro in Corsa', 'Sprint', 'Tiro Bloccante', 'Tiro Ravvicinato', 'Tiro Nascosto', 'Rischio Calcolato', 'Specialista Armatura'],
  },
  {
    id: 'arms_master', name: 'Maestro d\'Armi', roleId: 'warrior',
    armorTraining: 'Tutte le armature',
    weaponTraining: 'Tutte le armi',
    bonusCompetencies: ['Guerra', 'Armi'],
    equipmentPacks: ["Pacco del Soldato", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 5, essencesPerLevel: 1,
    essenceOptions: ['air', 'water', 'shadow'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Attacco Decisivo'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: ['Posizioni di Combattimento', 'Movimento Corazzato'], specialAbilityChoice: false },
      { level: 4, combatBonus: 1, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: ['Carica'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Arma Favorita', 'Esperto d\'Armi', 'Atterramento', 'Specialista Armatura'],
  },
  {
    id: 'beastmaster', name: 'Signore delle Bestie', roleId: 'scout',
    armorTraining: 'Tutte le armature',
    weaponTraining: 'Tutte le armi',
    bonusCompetencies: ['Guerra', 'Armi'],
    equipmentPacks: ["Pacco del Soldato", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 5, essencesPerLevel: 1,
    essenceOptions: ['air', 'nature', 'earth'],
    levelProgression: [
      { level: 1, combatBonus: 0, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Istinto del Cacciatore'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: ['Posizioni di Combattimento'], specialAbilityChoice: false },
      { level: 4, combatBonus: 0, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Comando Bestia'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Coordinazione Primordiale', 'Coordinazione Istintiva', 'Mente della Bestia', 'Reazione di Distress', 'Maestria Cavalcatura', 'Colpo Intimidatorio', 'Vista della Bestia', 'Addestramento Armatura Leggera'],
  },
  {
    id: 'berserker', name: 'Berserker', roleId: 'warrior',
    armorTraining: 'Armatura leggera',
    weaponTraining: 'Armi pesanti',
    bonusCompetencies: [],
    equipmentPacks: ["Pacco del Soldato", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 5, essencesPerLevel: 1,
    essenceOptions: ['fire', 'earth', 'nature'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Furia del Berserker', 'Pelle Dura'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 1, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Forza Interiore'], specialAbilityChoice: false },
      { level: 4, combatBonus: 1, defenseBonus: 0, attributeBonus: 1, healthBonus: 1, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Resistenza Notevole'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Sesto Senso', 'Ingoiare il Dolore', 'Duro come Pietra', 'Atterramento', 'Ignorare il Dolore', 'Mente Vuota', 'Furia Canalizzata', 'Grido di Battaglia (Paura)', 'Spinta Forte', 'Specialista Armatura'],
  },
  {
    id: 'paladin', name: 'Paladino', roleId: 'mystic',
    armorTraining: 'Armatura leggera/media/pesante',
    weaponTraining: 'Armi leggere/medie/pesanti',
    bonusCompetencies: [],
    equipmentPacks: ["Pacco del Soldato", "Pacco del Sacerdote"],
    skillPointsPerLevel: 5, essencesPerLevel: 1,
    essenceOptions: ['earth', 'fire', 'light'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Rettitudine del Paladino', 'Imposizione delle Mani'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Protezione Divina', 'Movimento Corazzato'], specialAbilityChoice: false },
      { level: 4, combatBonus: 0, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: ['Aura Divina'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Arma Favorita', 'Aura Potenziata', 'Aura di Guarigione', 'Aura di Chiarezza', 'Castigo Non-Morti', 'Castigo Demoni', 'Mani Guaritrici', 'Cerchio Protettivo', 'Arma Sacra', 'Forza Divina', 'Specialista Armatura'],
  },
  {
    id: 'priest', name: 'Sacerdote', roleId: 'mystic',
    armorTraining: 'Nessuna armatura',
    weaponTraining: 'Armi leggere',
    bonusCompetencies: ['Dei', 'Dio specifico', 'Culti'],
    equipmentPacks: ["Pacco dell'Accolito", "Pacco del Viaggiatore"],
    skillPointsPerLevel: 5, essencesPerLevel: 2,
    essenceOptions: ['light'],
    spells: ['Illuminare (luce)', 'Luce Sacra (luce)', 'Tempio (luce)', 'Prova (luce)', 'Aura di Speranza (luce)', 'Anello di Fuoco (fuoco)', 'Fortificare (terra)', 'Sussurro (aria)', 'Sigillo di Accesso (acqua)', 'Visione (sogno)'],
    levelProgression: [
      { level: 1, combatBonus: 0, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Iniziato Sacerdotale', 'Guida Spirituale'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Benevolenza'], specialAbilityChoice: false },
      { level: 3, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 4, combatBonus: 0, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: ['Comunita'], specialAbilityChoice: false },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
    ],
    specialAbilities: ['Incantesimi Extra', 'Sacrificio Altruista', 'Condotto degli Dei', 'Purificazione di Massa', 'Preghiere Solenni', 'Potenziato dalla Fede', 'Specialista Armatura'],
  },
  {
    id: 'ranger', name: 'Ranger', roleId: 'scout',
    armorTraining: 'Armatura leggera',
    weaponTraining: 'Armi medie',
    bonusCompetencies: ['Natura'],
    equipmentPacks: ["Pacco del Cacciatore", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 5, essencesPerLevel: 1,
    essenceOptions: ['earth', 'nature', 'shadow'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Nemico Giurato', 'Addestramento Armatura Leggera'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: ['Trappola del Cacciatore'], specialAbilityChoice: false },
      { level: 4, combatBonus: 0, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Adepto della Natura'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Arci-Nemico', 'Spostamento Rapido', 'Agguato del Cacciatore', 'Trappola Polvere Irritante', 'Veleno per Frecce', 'Trappola a Tagliola', 'Colori della Natura', 'Trappola Alchemica'],
  },
  {
    id: 'sentinel', name: 'Sentinella', roleId: 'agent',
    armorTraining: 'Tutte le armature',
    weaponTraining: 'Tutte le armi',
    bonusCompetencies: ['Etichetta'],
    equipmentPacks: ["Pacco del Soldato", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 6, essencesPerLevel: 1,
    essenceOptions: ['earth', 'water', 'light'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Protettore', 'Movimento Corazzato'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 0, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Posizioni di Combattimento'], specialAbilityChoice: false },
      { level: 4, combatBonus: 1, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Difesa Letale'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Arma Favorita', 'Esperto di Scudo', 'Colpo Stordente', 'Disarmo', 'Disciplina di Ferro', 'Colpo di Scudo', 'Interposizione', 'Spinta Forte', 'Parata Fluida', 'Corsa a Difendere', 'Grido di Battaglia (Coraggio)', 'Carica Scelta', 'Specialista Armatura'],
  },
  {
    id: 'summoner', name: 'Evocatore', roleId: 'spellweaver',
    armorTraining: 'Nessuna armatura',
    weaponTraining: 'Armi leggere',
    bonusCompetencies: ['Rituali', 'Spiriti'],
    equipmentPacks: ["Pacco dello Studioso", "Pacco del Viaggiatore"],
    skillPointsPerLevel: 5, essencesPerLevel: 2,
    essenceOptions: ['shadow', 'water', 'earth'],
    spells: ['Vampata (fuoco)', 'Dardo di Gelo (acqua)', 'Catene Oscure (ombra)', 'Armatura di Sabbia (terra)', 'Brace di Xyra (fuoco)', 'Crea Illusione (sogno)', 'Runa Sigillante (acqua)', 'Sabbie Mobili (terra)', 'Terrore (ombra)'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Compagno Spirituale', 'Scegli 3 incantesimi'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Competenza Rituale'], specialAbilityChoice: false },
      { level: 3, combatBonus: 0, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 4, combatBonus: 1, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: ['Spirito Potenziato'], specialAbilityChoice: false },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
    ],
    specialAbilities: ['Confluenza di Massa', 'Legame Spirituale', 'Vincolo del Velo', 'Passo del Velo Superiore', 'Vista dell\'Anima', 'Rinforzo Evocazione', 'Evocazione Stabile', 'Manifestazione Superiore', 'Maestro Evocatore'],
  },
  {
    id: 'swashbuckler', name: 'Spadaccino', roleId: 'rogue',
    armorTraining: 'Armatura leggera',
    weaponTraining: 'Armi medie',
    bonusCompetencies: [],
    equipmentPacks: ["Pacco del Viaggiatore", "Pacco del Cortigiano"],
    skillPointsPerLevel: 6, essencesPerLevel: 1,
    essenceOptions: ['water', 'air', 'dream'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Audacia', 'Addestramento Armatura Leggera'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: ['Provocazione'], specialAbilityChoice: false },
      { level: 4, combatBonus: 0, defenseBonus: 1, attributeBonus: 1, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Talento dello Spadaccino'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Vantaggio del Duellante', 'Slancio Stiloso', 'Finta', 'Colpo Audace', 'Fioretta', 'Gioco di Gambe', 'Passo Rapido', 'Parata Fluida', 'Duello Fluente', 'Fioretta Finale', 'Apertura Sporca', 'Chiacchiera Distraente', 'Movimento Imprevedibile'],
  },
  {
    id: 'thief', name: 'Ladro', roleId: 'rogue',
    armorTraining: 'Armatura leggera',
    weaponTraining: 'Armi leggere',
    bonusCompetencies: [],
    equipmentPacks: ["Pacco dello Scassinatore", "Pacco dell'Esploratore"],
    skillPointsPerLevel: 10, essencesPerLevel: 1,
    essenceOptions: ['shadow', 'dream', 'air'],
    levelProgression: [
      { level: 1, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Nascondersi Riflesso', 'Addestramento Armatura Leggera'], specialAbilityChoice: false },
      { level: 2, combatBonus: 1, defenseBonus: 0, attributeBonus: 0, healthBonus: 0, abilities: [], specialAbilityChoice: true },
      { level: 3, combatBonus: 0, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Scassinatore'], specialAbilityChoice: false },
      { level: 4, combatBonus: 1, defenseBonus: 0, attributeBonus: 1, healthBonus: 1, abilities: [], specialAbilityChoice: true },
      { level: 5, combatBonus: 1, defenseBonus: 1, attributeBonus: 0, healthBonus: 0, abilities: ['Consapevolezza Trappole'], specialAbilityChoice: false },
    ],
    specialAbilities: ['Pugnalata alle Spalle', 'Trattenere il Respiro', 'Competenza Trappole', 'Faccia Tosta', 'Routine dell\'Imbroglio', 'Agguato', 'Parata Rapida', 'Borseggio Migliorato'],
  },
];

export const SKILLS: Skill[] = [
  { id: 'charming', name: 'Charming', attribute: 'PRE', description: 'Conquistare gli altri, persuasione, calmare', passive: false },
  { id: 'climbing', name: 'Climbing', attribute: 'STR', description: 'Scalare superfici, aggrapparsi a sporgenze', passive: false },
  { id: 'deceiving', name: 'Deceiving', attribute: 'PRE', description: 'Mentire, bluffare, ingannare, giochi di prestigio', passive: false },
  { id: 'disguising', name: 'Disguising', attribute: 'PRE', description: 'Cambiare aspetto con oggetti/trucco', passive: false },
  { id: 'enduring', name: 'Enduring', attribute: 'VIT', description: 'Resistere al dolore, veleno, fatica', passive: true },
  { id: 'engineering', name: 'Engineering', attribute: 'FIN', description: 'Comprendere/manipolare meccanismi, trappole', passive: false },
  { id: 'evading', name: 'Evading', attribute: 'AGI', description: 'Schivare attacchi, incantesimi, pericoli', passive: true },
  { id: 'focusing', name: 'Focusing', attribute: 'MIN', description: 'Resistenza mentale, concentrazione', passive: true },
  { id: 'inferring', name: 'Inferring', attribute: 'SEN', description: 'Leggere intenzioni, individuare bugie, percepire motivi', passive: false },
  { id: 'investigating', name: 'Investigating', attribute: 'REA', description: 'Raccogliere informazioni, analizzare indizi', passive: false },
  { id: 'noticing', name: 'Noticing', attribute: 'SEN', description: 'Notare dettagli, consapevolezza, vigilanza', passive: false },
  { id: 'nursing', name: 'Nursing', attribute: 'REA', description: 'Valutare ferite, curare. Check riuscito (TV 15) = PV extra durante riposo', passive: false },
  { id: 'riding', name: 'Riding', attribute: 'FIN', description: 'Controllare cavalcature/veicoli', passive: false },
  { id: 'running', name: 'Running', attribute: 'STR', description: 'Volteggio, corsa sui muri, salto, parkour', passive: false },
  { id: 'sneaking', name: 'Sneaking', attribute: 'AGI', description: 'Muoversi inosservati, furtivita', passive: false },
  { id: 'swimming', name: 'Swimming', attribute: 'STR', description: 'Muoversi in acqua, immersione', passive: false },
];

export const WEAPONS: Weapon[] = [
  // Close Combat - Light
  { name: 'Pugnale', category: 'light', hands: 1, damage: '1d4', damageType: 'Perforante', properties: ['Lancio (6)'], attribute: 'AGI/STR', ranged: false },
  { name: 'Tirapugni', category: 'light', hands: 1, damage: '1d4', damageType: 'Contundente', properties: [], attribute: 'STR', ranged: false },
  { name: 'Accetta', category: 'light', hands: 1, damage: '1d4', damageType: 'Tagliente', properties: ['Uncino', 'Lancio (5)'], attribute: 'STR', ranged: false },
  // Close Combat - Medium
  { name: 'Ascia a Mano', category: 'medium', hands: 1, damage: '1d6', damageType: 'Tagliente', properties: ['Uncino'], attribute: 'STR', ranged: false },
  { name: 'Spada Corta', category: 'medium', hands: 1, damage: '1d6', damageType: 'Perforante', properties: [], attribute: 'AGI', ranged: false },
  { name: 'Mazza', category: 'medium', hands: 1, damage: '1d6', damageType: 'Contundente', properties: [], attribute: 'STR', ranged: false },
  { name: 'Bastone', category: 'medium', hands: 2, damage: '1d6', damageType: 'Contundente', properties: [], attribute: 'AGI', ranged: false },
  { name: 'Stocco', category: 'medium', hands: 1, damage: '1d6', damageType: 'Perforante', properties: [], attribute: 'AGI', ranged: false },
  { name: 'Flagello', category: 'medium', hands: 1, damage: '1d8', damageType: 'Contundente', properties: ['Uncino'], attribute: 'STR', ranged: false },
  { name: 'Stella del Mattino', category: 'medium', hands: 1, damage: '1d8', damageType: 'Perf./Cont.', properties: [], attribute: 'STR', ranged: false },
  { name: 'Tridente', category: 'medium', hands: 2, damage: '1d8', damageType: 'Perforante', properties: ['Portata (1)', 'Lancio (5)'], attribute: 'STR', ranged: false },
  { name: 'Khopesh', category: 'medium', hands: 1, damage: '1d8', damageType: 'Tagliente', properties: ['Uncino'], attribute: 'AGI', ranged: false },
  // Close Combat - Heavy
  { name: 'Falcione', category: 'heavy', hands: 2, damage: '1d10', damageType: 'Tagliente', properties: ['Portata (1)'], attribute: 'AGI', ranged: false },
  { name: 'Maglio', category: 'heavy', hands: 2, damage: '2d6', damageType: 'Contundente', properties: [], attribute: 'STR', ranged: false },
  { name: 'Ascia Bipenne', category: 'heavy', hands: 2, damage: '2d6', damageType: 'Tagliente', properties: ['Uncino'], attribute: 'STR', ranged: false },
  { name: 'Spadone', category: 'heavy', hands: 2, damage: '1d12', damageType: 'Tagliente', properties: [], attribute: 'STR', ranged: false },
  // Ranged
  { name: 'Amentum', category: 'light', hands: 1, damage: '1d6', damageType: 'Perforante', properties: ['Lancio'], attribute: 'STR', ranged: true },
  { name: 'Balestra', category: 'medium', hands: 2, damage: '1d8', damageType: 'Perforante', properties: ['Gittata (16)', 'Ricarica'], attribute: 'FIN', ranged: true },
  { name: 'Arco Ricurvo', category: 'medium', hands: 2, damage: '1d8', damageType: 'Perforante', properties: ['Gittata (18)', 'Cavalcatura'], attribute: 'FIN', ranged: true },
  { name: 'Arbalesta', category: 'heavy', hands: 2, damage: '1d12', damageType: 'Perforante', properties: ['Gittata (20)', 'Ricarica'], attribute: 'FIN', ranged: true },
];

export const ARMORS: Armor[] = [
  { name: 'Nessuna Armatura', category: 'none', tier: 0, armorPoints: 0, movementPenalty: 0, skillPenalty: 0 },
  { name: 'Armatura Leggera T1', category: 'light', tier: 1, armorPoints: 4, movementPenalty: 0, skillPenalty: -1 },
  { name: 'Armatura Leggera T2', category: 'light', tier: 2, armorPoints: 8, movementPenalty: 0, skillPenalty: -2 },
  { name: 'Armatura Leggera T3', category: 'light', tier: 3, armorPoints: 12, movementPenalty: 0, skillPenalty: -3 },
  { name: 'Armatura Media T1', category: 'medium', tier: 1, armorPoints: 16, movementPenalty: -1, skillPenalty: -4 },
  { name: 'Armatura Media T2', category: 'medium', tier: 2, armorPoints: 20, movementPenalty: -1, skillPenalty: -5 },
  { name: 'Armatura Media T3', category: 'medium', tier: 3, armorPoints: 24, movementPenalty: -1, skillPenalty: -6 },
  { name: 'Armatura Pesante T1', category: 'heavy', tier: 1, armorPoints: 28, movementPenalty: -2, skillPenalty: -7 },
  { name: 'Armatura Pesante T2', category: 'heavy', tier: 2, armorPoints: 32, movementPenalty: -2, skillPenalty: -8 },
  { name: 'Armatura Completa', category: 'heavy', tier: 3, armorPoints: 36, movementPenalty: -3, skillPenalty: -12 },
];

export const SHIELDS: Shield[] = [
  { name: 'Brocchiere', defenseBonus: 1 },
  { name: 'Scudo', defenseBonus: 2 },
  { name: 'Scudo a Goccia', defenseBonus: 3 },
];

export const EQUIPMENT_PACKS: EquipmentPack[] = [
  {
    name: "Pacco dello Studioso",
    items: ['Cintura', 'Borsa', 'Bisaccia', 'Lampada da lettura', 'Custodie per pergamene x3', 'Tomo di riferimento', 'Quaderno', 'Sacco a pelo'],
    weaponOptions: ['Bastone', 'Pugnale', 'Fionda + 20 pietre'],
    armorOptions: ['Abiti da studioso', 'Armatura imbottita', 'Maglia di scaglie'],
  },
  {
    name: "Pacco dello Scassinatore",
    items: ['Cintura', 'Borsa in pelle', 'Grimaldelli', 'Piede di porco piccolo', 'Borselli x2', 'Corda di seta', 'Mantello scuro con cappuccio', 'Sacco a pelo'],
    weaponOptions: ['Spada Corta', 'Arco Corto + 20 frecce', 'Pugnale'],
    armorOptions: ['Abiti da viaggio', 'Armatura di cuoio', 'Armatura ad anelli'],
  },
  {
    name: "Pacco dell'Esploratore",
    items: ['Cintura', 'Zaino da viaggio', 'Sacco a pelo', 'Kit da cucina', 'Acciarino', 'Torce x10', 'Razioni (3 giorni)', 'Otre'],
    weaponOptions: ['Lancia', 'Arco Lungo + 20 frecce', 'Bastone'],
    armorOptions: ['Abiti da viaggio', 'Brigantina', 'Cotta di maglia'],
  },
  {
    name: "Pacco del Soldato",
    items: ['Cintura tattica', 'Zaino militare', 'Sacco a pelo', 'Pietra per affilare', 'Razioni (3 giorni)', 'Bende di ricambio', 'Olio per armi', 'Corda'],
    weaponOptions: ['Spada Corta', 'Spada Lunga', 'Alabarda'],
    armorOptions: ['Uniforme/Tunica', 'Cotta di maglia', 'Corazza'],
  },
  {
    name: "Pacco del Diplomatico",
    items: ['Cintura elegante', 'Bisaccia diplomatica', 'Mantello pregiato', 'Ceralacca e sigillo', 'Carta e penne', 'Bottiglia di vino', 'Dono/token', 'Libro mastro', 'Sacco a pelo'],
    weaponOptions: ['Stocco', 'Balestra + 20 dardi', 'Pugnale'],
    armorOptions: ['Abiti da corte', 'Armatura di cuoio', 'Brigantina'],
  },
];

export const ANIMAL_COMPANIONS = [
  'Orso (Combattimento, Cavalcatura)',
  'Lupo (Combattimento, Utilita)',
  'Cervo (Cavalcatura, Combattimento)',
  'Cinghiale (Combattimento, Cavalcatura)',
  'Falco (Combattimento, Esplorazione)',
  'Tasso (Utilita, Combattimento)',
  'Ratto (Utilita, Esplorazione)',
  'Puma (Combattimento, Esplorazione)',
  'Gatto (Esplorazione, Utilita)',
  'Lepre (Utilita, Esplorazione)',
  'Capra (Cavalcatura)',
  'Cavallo (Cavalcatura)',
  'Serpente (Utilita)',
  'Lucertola (Utilita)',
];

export const ESSENCE_NAMES: Record<string, string> = {
  light: 'Luce',
  shadow: 'Ombra',
  fire: 'Fuoco',
  water: 'Acqua',
  earth: 'Terra',
  air: 'Aria',
  nature: 'Natura',
  dream: 'Sogno',
};

export const ATTRIBUTE_POINT_BUDGET = 8; // Total points to distribute at creation
